### ISSUE TITLE
SIGKILL / SIGABRT Worker Timeout due to opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error

### ISSUE THREAD

**Issue by jp-pelegrino** [beak-insights/felicity-lims#42]
The commits few days ago resolved the issue I had in #40 and #39

Although the `felicity-api` workers keeps getting a `WORKER TIMEOUT` to `SIGKILL` errors preventing the user to be able to login

On the browser console, I am getting

`WebSocker connection to 'ws://172.104.180.162/felicity-gql' failed: WebSocket is closed before the connection is established.`

Reviewing the logs and is also mentioned on https://github.com/beak-insights/felicity-lims/issues/39#issuecomment-2327170905 , this error:

```
felicity-aio  | WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting traces to 192.168.0.40:4317, retrying in 8s.
```

After I modify the `.env` configuration so that `RUN_OPEN_TRACING=False` instead of `True`, it resolved the issue for me

A revision on the env.example might be needed so that the default value for `RUN_OPEN_TRACING` is set to `False` instead of `True` , or integration of Application Monitoring on the docker compose and/or the modification of `OTLP_SPAN_EXPORT_URL=http://192.168.0.40:4317` , specifically the default IP address

Thank you!

**Comment by aurthurm** [comment]
disable open telemetry with RUN_OPEN_TRACING=False

Noted ill change the default value to false

**Comment by aurthurm** [comment]
if you are facing challenges lets do anydesk so i can help you out
